# Generated by Django 4.2.3 on 2023-07-05 02:35

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_post_like_users_alter_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=django_resized.forms.ResizedImageField(
                crop=["middle"],
                force_format=None,
                keep_meta=True,
                quality=-1,
                scale=None,
                size=[500, 500],
                upload_to="pic/%m/%d",
            ),
        ),
    ]
